### ISSUE TITLE
aggregator does not accurately track burgers that are in two locations

### ISSUE THREAD

**Issue by jonathangreen** [qadan/qadan.github.io#15]
Test case: 
http://peiburgerlove.ca/burger/Turfs-Bar-And-Grill

First item on map on page is aggregated. Second map on page is not aggregated into the BATT ![](http://icons.iconarchive.com/icons/gcds/halloween/256/bat-icon.png)
. 

This deprives the good people of ScummerSide :hocho: of a delicious burger. 

:hamburger::hamburger::hamburger::hamburger:

**Comment by qadan** [comment]
HOW CAN BURGER BE IN TWO PLACE AT ONCE

this is madness

**Comment by qadan** [comment]
proposed solution: as this appears to be the only hyperburger, add an edge case into the burger scraper to manually add the address to the resultant JSON

**Comment by qadan** [comment]
should be addressed in https://github.com/qadan/qadan.github.io/commit/faefc550aaf3711b3fea92bcac88eb8716873923

the restaurant ID for each restaurant is the same because the burger is the same, so the status is shared between the two. however, currently the $("#i-forget-what-the-button-id-is").each() isn't iterating over both buttons when changing the status, so I'll have to fix that. The status does change though, and so does the marker icon

**Comment by qadan** [comment]
Handled properly in https://github.com/qadan/qadan.github.io/commit/666eab4210ef950b9daad562d26ca6f4f3db1832

A method is set to handle the hyperburger; plus, things have been moved around so that the restaurant information is stored as infoWindow.restaurant_content, the infoWindow status is stored as infoWindow.burger_status, and the restaurant's infoWindow can be regenerated on the fly using infoWindow.regenerateContent(). This should also save some time on initial page load not having to generate all 61 infoWindows.

The logic has been overhauled so many times now that things have gotten pretty messy. I'm gonna make a 0.2 sometime soon, but for now this is working.
